# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oEbLT4-U2-lglLPCtJioDGKHHEhuB9Ti
"""

import random 
import string

print("Hello dear user, welcome to Pssword wold")
print("Give yourself the gift of security")

length=int(input("enter please the length of password:"))

lowercharacters = string.ascii_lowercase
uppercharacters = string.ascii_uppercase
numbers= string.digits
symbols = string.punctuation 

easy_to_say = lowercharacters 
easy_to_read = lowercharacters + uppercharacters + numbers
all_characters = lowercharacters + uppercharacters + numbers + symbols


The_answer =input("Choose please what form your password will be * easy_to_say , easy_to_read or all_characters * : ")

if The_answer == "easy_to_say":
  x = random.sample(easy_to_say,length)
  password ="".join(x)
  print(password)
elif The_answer == "easy_to_read":
  x = random.sample(easy_to_read,length)
  password ="".join(x)
  print(password)
elif The_answer == "all_characters":
  x = random.sample(all_characters,length)
  password ="".join(x)
  print(password)
else:
  print("sorry, you wrote something incorrectly")